Win32 build fixes
- "n." makefile syntax error, introduced by commit "attributes 0.26_01c"

- using a var for array length apparantly isn't a constant expression
  according to Visual C which is C89
..\xsutils.c(713) : error C2057: expected constant expression
..\xsutils.c(713) : error C2466: cannot allocate an array of constant size 0
..\xsutils.c(713) : error C2133: 'name' : unknown size

- add pp_type.c as core .o file,
globals.obj : error LNK2001: unresolved external symbol _Perl_pp_i_aelem

- \ paths cause win32's copy command to fatally error, change to / paths

- on a rebuild, (mini) Config.pm can't be written to since it is Config XS
  last created it, and EUMM makes all built things RO with chmod, so
  de-readonly it to undo the RO attribute EUMM added

-#ifdef inside a CPP macro is illegal
        cl -c    -nologo -GF -W3 -Od -MD -Zi -DNDEBUG -GL -DWIN32 -D_CONSOLE -DN
O_STRICT -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -D_
USE_32BIT_TIME_T -DPERLDLL -Od -MD -Zi -DNDEBUG -GL    -DVERSION=\"2.00c\"  -DXS
_VERSION=\"2.00c\"  "-I..\..\lib\CORE"  -DLIBC="msvcrt.lib" DynaLoader.c
DynaLoader.c
c:\sources\cperl\ext\DynaLoader\dlutils.c(1070) : error C2121: '#' : invalid cha
racter : possibly the result of a macro expansion
c:\sources\cperl\ext\DynaLoader\dlutils.c(1070) : error C2146: syntax error : mi
ssing ')' before identifier 'ifdef'
c:\sources\cperl\ext\DynaLoader\dlutils.c(1070) : error C2144: syntax error : '<
Unknown>' should be preceded by '<Unknown>'
c:\sources\cperl\ext\DynaLoader\dlutils.c(1070) : error C2144: syntax error : '<
Unknown>' should be preceded by '<Unknown>'
c:\sources\cperl\ext\DynaLoader\dlutils.c(1070) : error C2143: syntax error : mi
ssing ')' before 'identifier'
c:\sources\cperl\ext\DynaLoader\dlutils.c(1070) : error C2121: '#' : invalid cha
racter : possibly the result of a macro expansion
c:\sources\cperl\ext\DynaLoader\dlutils.c(1070) : error C2121: '#' : invalid cha
racter : possibly the result of a macro expansion
c:\sources\cperl\ext\DynaLoader\dlutils.c(1070) : error C2121: '#' : invalid cha
racter : possibly the result of a macro expansion
c:\sources\cperl\ext\DynaLoader\dlutils.c(1070) : error C2121: '#' : invalid cha
racter : possibly the result of a macro expansion
c:\sources\cperl\ext\DynaLoader\dlutils.c(1070) : error C2121: '#' : invalid cha
racter : possibly the result of a macro expansion
NMAKE : fatal error U1077: 'cl' : return code '0x2'
Stop.
Unsuccessful make(ext/DynaLoader): code=512 at ..\make_ext.pl line 575.

-rename perlbug, perldoc and perlivp, they were renamed in
 commit "cperl: update INSTALL, perlbug, perldoc" but not for win32

-downgrade 5.23 in the makefiles to 5.22